Add Status field to Person
AY2021S1-CS2103-F09-2/tp pull request #80
Opened 2020-10-04 14:07 UTC by esmanda3w

2020-10-04 15:23 UTC, Vielheim requested changes

2020-10-04 15:23 UTC, Vielheim commented on src/main/java/seedu/address/model/person/Status.java
> +        return Status.valueOf(status);
Maybe you would like to use "toUpper" here? Less bugs

2020-10-04 15:23 UTC, Vielheim commented on src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
> +    private static final String INVALID_STATUS = "active";
Perhaps you can consider not using "active" here? Probably can use some gibberish like "asdjnewfpqwifnqiweyfbqwekfbrw"?

2020-10-06 03:58 UTC, CodyChew approved these changes
LGTM.

2020-10-06 04:05 UTC, Vielheim approved these changes

2020-10-06 05:27 UTC, merged